### ISSUE TITLE
Capacitor 3 Documentation

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/capacitor-site#143]
BETA

- [x] [Using with Ionic](https://capacitorjs.com/docs/v3/getting-started/with-ionic) 
- [ ] Upgrade Guide for apps
    - [x] Check for permissions that can be removed from `AndroidManifest.xml`
    - [ ] ~Warn about usage of ESM for Jest and other testing frameworks~
    - [ ] ~https://github.com/ionic-team/capacitor/pull/4093/files~ https://github.com/ionic-team/capacitor-site/issues/220 and https://github.com/ionic-team/capacitor-site/issues/221
    - [ ] ~Guide to switch from JS to TS config files~ https://github.com/ionic-team/capacitor-site/issues/222
- [ ] ~Upgrade Guide for plugins~ https://github.com/ionic-team/capacitor-site/issues/223 and https://github.com/ionic-team/capacitor-site/issues/224
- [ ] ~"Sync Project with Gradle Files"~ https://github.com/ionic-team/capacitor-site/issues/225
- [x] Basics -> Progressive Web Apps
- [x] Plugin API documentation 
    - [x] Plugin examples and additional docs
- [x] [Creating Plugins](https://capacitorjs.com/docs/v3/plugins/creating-plugins) section
    - [x] Overview: should mention Capacitor community, how to get involved, how proposals work, etc.
    - [x] Development Workflow updates
        - [x] shouldn't advise `npm link`, just `npm install` with a path
        - [x] needs to be updated with new tooling in plugins, etc
    - [x] iOS Guide
        - [x] Permissions 
        - [x] Error codes: unavailable/unimplemented
    - [x] Android Guide
        - [x] Permissions 
        - [x] [Intents with Result(s)](https://capacitorjs.com/docs/v3/plugins/android#intents-with-results) @carlpoole 
        - [x] Error codes: unavailable/unimplemented
    - [x] Web/PWA Guide
        - [x] Permissions
        - [x] Error codes: unavailable/unimplemented
    - [x] JavaScript Guide
- [x] https://github.com/ionic-team/capacitor-site/issues/96
- [x] https://github.com/ionic-team/capacitor-site/issues/14
- [x] Web/PWA
    - [ ] ~PWA Elements page~

RC
- [ ] ~Show `<reference` additions for plugins that have configuration~ https://github.com/ionic-team/capacitor-plugins/issues/236
